### PR TITLE
Biome Builder

### PR DESCRIPTION
**Pull request by arthurbambou**

### CODE REVIEW

**Comment by arthurbambou** [comment]
Still need to make testmod

**Comment by arthurbambou** [comment]
datapacks doesn't seems to load automatically in world creation screen

**Comment by natanfudge** [comment]
@arthurbambou Are these visible `ArtificeResourcePackContainer`s? What do you mean by "buffet world" and needing to first "load the datapack"?

**Comment by thecatcore** [comment]
[When you choose the Single Biome without looking at the datapacks](https://cdn.discordapp.com/attachments/452162170533445636/730902930949013514/2020-07-09_23.44.36.png)
[no custom biome](https://cdn.discordapp.com/attachments/452162170533445636/730902928361128097/2020-07-09_23.45.03.png)
[When I look at the datapacks](https://cdn.discordapp.com/attachments/452162170533445636/730902925508870214/2020-07-09_23.45.15.png)
[Then after I enabled the datapack](https://cdn.discordapp.com/attachments/452162170533445636/730902921881059379/2020-07-09_23.45.35.png)

**Comment by natanfudge** [comment]
Check if you have the problem now if you pull new changes

**Comment by thecatcore** [comment]
The Datapack seems to be in the "loaded" column of the datapack screen, but I still need to press "Done" for it to load. :thinking:

**Comment by thecatcore** [comment]
I think I'm gonna close #13 and #14 and merge them in this one because they are small ones.

**Comment by natanfudge** [comment]
> The Datapack seems to be in the "loaded" column of the datapack screen, but I still need to press "Done" for it to load. 🤔

Can you please test if this issue happens when you add biome data packs normally (as a json resource)? If it does work for you tell me how you add them so I can figure out how they work.

**Comment by thecatcore** [comment]
:thinking: 
I mean it's normal because vanilla doesn't have a global datapack folder and only the vanilla datapack is supposed to be preloaded when you enter world creation screen.

**Comment by thecatcore** [comment]
And yes it does happen when using json datapacks.

**Comment by natanfudge** [comment]
I think I’m going to wait until there’s more mappings or Mojang change something until I try to solve it then. If you can figure it out yourself then that works too.

**Comment by thecatcore** [comment]
fixed :sweat_smile:

**Pull request merged**
