### PR TITLE
Add DimensionTypeBuilder and DimensionBuilder

### PR DESCRIPTION
**Pull request by arthurbambou**
- [x] Create DimensionTypeBuilder
- [x] Create DimensionBuilder

- [x] Test mod implementation vanilla
- [x] Test mod implementation custom chunk generator

- [x] Finish Javadoc

### CODE REVIEW

**Comment by arthurbambou** [comment]
Please review.

**Comment by natanfudge** [comment]
Oh, sorry, I didn't notice you finished this. I will get to this right away.

**Comment by natanfudge** [comment]
Seems good, even has tests.

**Comment by natanfudge** [comment]
This is part of `0.8.0+1.16-rc1`

**Pull request merged**
